swagger: "2.0"
info:
  version: "0.0.1"
  title: API for accessing GTFS data for VTA
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /gtfs/vta
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: {}
x-a127-services:
  global_cache:
#        provider: volos-cache-apigee
        provider: volos-cache-memory
        options:
          fallback: true
          name: gtfs_cache
          ttl: 60000
  trip_cache:
#        provider: volos-cache-apigee
        provider: volos-cache-memory
        options:
          name: trip_cache
          ttl: 60000
paths:
  /updates:
    # binds a127 app logic to a route
    x-swagger-router-controller: gtfs
    x-a127-apply:
      global_cache: {}
    get:
      description: Returns all trip updates
      # used as the method name of the controller
      operationId: updates
      parameters:
        - name: api_key
          in: query
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /trips/{tripId}/updates:
    # binds a127 app logic to a route
    x-swagger-router-controller: gtfs
    x-a127-apply:
      trip_cache: {}
    get:
      description: Returns updates for a specific trip
      # used as the method name of the controller
      operationId: updatesByTrip
      parameters:
        - name: api_key
          in: query
          required: true
          type: string
        - name: tripId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
